# Generated by Django 4.2 on 2025-10-20 19:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_sensorbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('vault', 'HashiCorp Vault'), ('azure_kv', 'Azure Key Vault'), ('aws_sm', 'AWS Secrets Manager'), ('local_enc', 'Local Encrypted Storage')], help_text='Secret management provider', max_length=20)),
                ('path', models.CharField(help_text='Path or identifier in the secret provider', max_length=500)),
                ('key', models.CharField(help_text='Specific key/field name within the secret', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for secret retrieval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_refs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Secret Reference',
                'verbose_name_plural': 'Secret References',
                'db_table': 'storage_secret_ref',
            },
        ),
        migrations.CreateModel(
            name='StorageProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable profile name', max_length=100)),
                ('backend', models.CharField(choices=[('azure', 'Azure Blob Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO / S3-compatible'), ('local', 'Local Filesystem')], help_text='Storage backend type', max_length=20)),
                ('region', models.CharField(blank=True, help_text='Region or location (for cloud providers)', max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default storage profile for the tenant')),
                ('config', models.JSONField(default=dict, help_text='Backend-specific configuration (excluding secrets). Examples: bucket_name, container_name, base_path, endpoint_url')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_ref', models.ForeignKey(blank=True, help_text='Reference to stored credentials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_profiles', to='storage.secretref')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_profiles', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Storage Profile',
                'verbose_name_plural': 'Storage Profiles',
                'db_table': 'storage_profile',
            },
        ),
        migrations.AddIndex(
            model_name='storageprofile',
            index=models.Index(fields=['tenant', 'is_default'], name='storage_pro_tenant__778f80_idx'),
        ),
        migrations.AddIndex(
            model_name='storageprofile',
            index=models.Index(fields=['tenant', 'backend'], name='storage_pro_tenant__aa0a7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storageprofile',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='secretref',
            index=models.Index(fields=['tenant', 'provider'], name='storage_sec_tenant__86a6d0_idx'),
        ),
    ]
