# Generated by Django 4.2 on 2025-10-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_description_organization_slug'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='secretref',
            name='storage_sec_tenant__86a6d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='storageprofile',
            name='storage_pro_tenant__778f80_idx',
        ),
        migrations.RemoveIndex(
            model_name='storageprofile',
            name='storage_pro_tenant__aa0a7f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='storageprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='secretref',
            name='tenant',
        ),
        migrations.AddField(
            model_name='secretref',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secret_refs', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageprofile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_profiles', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='storageprofile',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='secretref',
            index=models.Index(fields=['organization', 'provider'], name='storage_sec_organiz_9321bb_idx'),
        ),
        migrations.AddIndex(
            model_name='storageprofile',
            index=models.Index(fields=['organization', 'is_default'], name='storage_pro_organiz_698fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='storageprofile',
            index=models.Index(fields=['organization', 'backend'], name='storage_pro_organiz_d231df_idx'),
        ),
        migrations.AddIndex(
            model_name='storageprofile',
            index=models.Index(fields=['is_active'], name='storage_pro_is_acti_176fd6_idx'),
        ),
        migrations.RemoveField(
            model_name='storageprofile',
            name='tenant',
        ),
    ]
