# Generated by Django 4.2 on 2025-10-21 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_remove_organization_description_organization_slug'),
        ('storage', '0002_remove_secretref_storage_sec_tenant__86a6d0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text='Unique identifier for this secret', max_length=255)),
                ('encrypted_value', models.TextField(help_text='Fernet-encrypted secret data')),
                ('description', models.TextField(blank=True, help_text='Description of what this secret is for')),
                ('encryption_version', models.PositiveSmallIntegerField(default=1, help_text='Encryption key version used for this secret')),
                ('last_decrypted_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful decryption (for audit)', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_secrets', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encrypted Secret',
                'verbose_name_plural': 'Encrypted Secrets',
                'db_table': 'storage_encrypted_secret',
            },
        ),
        migrations.AddIndex(
            model_name='encryptedsecret',
            index=models.Index(fields=['organization', 'identifier'], name='storage_enc_organiz_eb3c2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='encryptedsecret',
            unique_together={('organization', 'identifier')},
        ),
    ]
