version: '3.3'

services:
  # computing unit
  cvision-dl-ops:
    image: tannousgeagea/cvisionops:latest
    container_name: cvision-ops-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    networks:
      - internal
    ports:
      - 29081-29085:29081-29085
    env_file: .env
    restart: unless-stopped
    working_dir: /home/$user/src
    volumes:
      - .:/home/$user/src
      - /media/$user/cvision-mlops-media:/media/
    user: ${user}
    depends_on:
      - rabbitmq
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /media/$user/cvision-mlops-media:/media
    depends_on:
      - cvision-dl-ops

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: cvision-ops-rabbitmq
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_INTERFACE_PORT}:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:latest
    container_name: cvision-ops-postgres
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
     - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  internal:
    driver: bridge 

volumes:
  postgres_data: