version: '3.3'

services:
  # computing unit
  cvision-dl-ops:
    image: wasteant/wasteant:cvision-dl-ops-ubuntu.22.04-cuda.12.5.1-dev
    container_name: cvision-dl-ops-incremental-learning-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    network_mode: host
    env_file: .env
    restart: unless-stopped
    working_dir: /home/$user/src
    volumes:
      - .:/home/$user/src
      - /media/$user/cvision-mlops-media:/media/
    user: ${user}

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: cvision-dl-ops-incremental-learning-rabbitmq
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_INTERFACE_PORT}:15672"
    volumes:
      - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq-cvision-dl-ops-incremental-learning
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  rabbitmq-cvision-dl-ops-incremental-learning:
    driver: bridge 