# Generated by Django 4.2 on 2024-12-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_edge_box_image_sensorbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='mode',
        ),
        migrations.DeleteModel(
            name='ImageMode',
        ),
    ]
