name: Auto Tag (Minor | Patch) Version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag and bump
        id: version
        run: |
          # Get latest tag
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "0.0.0")

          # Remove 'v' prefix
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Decide bump type
          BUMP_TYPE="${{ github.event.inputs.bump }}"

          if [[ "$BUMP_TYPE" == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ "$BUMP_TYPE" == "patch" ]]; then
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New version will be: $NEW_TAG"

      - name: Create and push new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
          git push origin "$NEW_TAG"
